### PR TITLE
[SOFTWARE-5318] Add image_name input variable to container actions

### PR DESCRIPTION
**Pull request by AidenCohen31**

### CODE REVIEW

**Review by brianhlin — COMMENTED** [review]
Doesn't this also need the case fixes?

**Comment by brianhlin** [comment]
Hey @AidenCohen31, thanks for merging the suggestions but I think you also need to apply the same case fix that the other action repos got

**Comment by AidenCohen31** [comment]
Gotcha

**Comment by AidenCohen31** [comment]
fixed

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
